# Generated by Django 4.2.6 on 2023-11-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daisies', '0002_remove_bandmember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='image',
            field=models.ImageField(blank=True, default='BAND/static/images/', null=True, upload_to='band_members/'),
        ),
    ]
